@ECHO ON
IF NOT DEFINED SELF (
    set SELF=%APPVEYOR_PROJECT_NAME:-=_%
)
REM Handle old appveyor configs
IF DEFINED CXXFLAGS (
  SET B2_CXXFLAGS=%CXXFLAGS%
  SET CXXFLAGS=
)
SET BOOST_CI_TARGET_BRANCH=%APPVEYOR_REPO_BRANCH%
SET BOOST_CI_SRC_FOLDER=%APPVEYOR_BUILD_FOLDER%

%~dp0\..\common_install.bat
