#
# Copyright 2020-2021 Peter Dimov
# Copyright 2021 Andrey Semashev
# Copyright 2021-2026 Alexander Grund
# Copyright 2022-2025 James E. King III
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# This workflow uses the Boost.CI reusable workflow to test the `exclude_jobs` input.
#
---
name: Test.ExcludeJobs.CI

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - bugfix/**
      - feature/**
      - fix/**
      - pr/**
    paths-ignore:
      - LICENSE
      - meta/**
      - README.md

jobs:
  call-boost-ci:
    name: Run Boost.CI
    uses: boostorg/boost-ci/.github/workflows/reusable.yml@master
    with:
      exclude_jobs: |
        os: ubuntu-1 # Remove Ubuntu 16/18 jobs (substring match)
        # Remove all jobs where compiler is any of those
        compiler: 'gcc-7,gcc-9,gcc-10,gcc-11,gcc-12'
        # Remove the MacOS sanitizer job
        os: macos-14, sanitize: yes

        # Empty line and comment
        # Reduce cxxstd of clang-22 jobs by removing C++14 & C++17
        compiler: 'gcc-7,clang-22', cxxstd: '14,17'
        # Remove all cxxstd -> Job removed
        compiler: clang-6.0, cxxstd: '11,14,17'
        # No matching cxxstd -> Job unmodified
        compiler: clang-7, cxxstd: '20,23,26'
        "coverage":"yes" # Missing space after colon -> Requires quoting
        "type": cmake, os: ubuntu # No CMake tests on Linux